/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2020-2021, The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _AIS_IFE_CSID_780_H_
#define _AIS_IFE_CSID_780_H_

#include "ais_ife_csid_core.h"

static struct ais_ife_csid_ver2_top_reg_info
			ais_ife_csid_780_top_reg_info = {
	.io_path_cfg0_addr = {
		0x0,
		0x4,
		0x8,
	},
	.dual_csid_cfg0_addr =  {
		0xC,
		0x10,
		0x14,
	},
	.input_core_type_shift_val      = 0,
	.sfe_offline_en_shift_val       = 12,
	.out_ife_en_shift_val           = 8,
	.dual_sync_sel_shift_val        = 8,
	.dual_en_shift_val              = 0,
	.master_slave_sel_shift_val     = 1,
	.rdi_lcr_shift_val              = 16,
	.master_sel_val                 = 0,
	.slave_sel_val                  = 1,
	.io_path_cfg_rst_val            = 1,
	.dual_cfg_rst_val               = 0,
};

static struct ais_ife_csid_common_reg_offset
			ais_ife_csid_780_cmn_reg_offset = {
	.csid_hw_version_addr                         = 0x0,
	.csid_cfg0_addr                               = 0x4,
	.csid_ctrl_addr                               = 0x8,
	.csid_reset_addr                              = 0xc,
	.csid_rst_strobes_addr                        = 0x10,

	.csid_test_bus_ctrl_addr                      = 0x1EB,
	.csid_top_irq_status_addr                     = 0x7C,
	.csid_top_irq_mask_addr                       = 0x80,
	.csid_top_irq_clear_addr                      = 0x84,
	.csid_top_irq_set_addr                        = 0x88,
	.csid_irq_cmd_addr                            = 0x14,

	.csid_buf_done_irq_status_addr                = 0x8C,
	.csid_buf_done_irq_mask_addr                  = 0x90,
	.csid_buf_done_irq_clear_addr                 = 0x94,

	.rup_aup_cmd_addr                             = 0x18,

	/*configurations */
	.major_version                                = 6,
	.minor_version                                = 8,
	.version_incr                                 = 0,
	.num_rdis                                     = 3,
	.num_pix                                      = 1,
	.num_ppp                                      = 1,
	.csid_reg_rst_stb                             = 0x2,
	.csid_rst_stb                                 = 0x1,
	.csid_rst_stb_sw_all                          = 0x1f,
	.path_rst_stb_all                             = 0x00,
	.path_rst_done_shift_val                      = 1,
	.path_en_shift_val                            = 31,
	.dt_id_shift_val                              = 27,
	.vc_shift_val                                 = 22,
	.dt_shift_val                                 = 16,
	.fmt_shift_val                                = 12,
	.plain_fmt_shit_val                           = 12,
	.crop_v_en_shift_val                          = 8,
	.crop_h_en_shift_val                          = 7,
	.crop_shift                                   = 16,
	.ipp_irq_mask_all                             = 0x7FFF,
	.rdi_irq_mask_all                             = 0x7FFF,
	.ppp_irq_mask_all                             = 0xFFFF,
	.measure_en_hbi_vbi_cnt_mask                  = 0xc,
	.format_measure_en_val                        = 1,
	.format_measure_height_mask_val               = 0xFFFF,
	.format_measure_height_shift_val              = 0x10,
	.format_measure_width_mask_val                = 0xFFFF,
	.format_measure_width_shift_val               = 0x0,

	.epoch_factor                                 = 50,
	.buf_done_shitf_val                           = 14,
};

static struct ais_ife_csid_csi2_rx_reg_offset
			ais_ife_csid_780_csi2_reg_offset = {
	.csid_csi2_rx_irq_status_addr                 = 0x9c,
	.csid_csi2_rx_irq_mask_addr                   = 0xA0,
	.csid_csi2_rx_irq_clear_addr                  = 0xA4,
	.csid_csi2_rx_irq_set_addr                    = 0xA8,

	/*CSI2 rx control */
	.csid_csi2_rx_cfg0_addr                       = 0x200,
	.csid_csi2_rx_cfg1_addr                       = 0x204,
	.csid_csi2_rx_capture_ctrl_addr               = 0x208,
	.csid_csi2_rx_rst_strobes_addr                = 0x20C,
	.csid_csi2_rx_de_scramble_cfg0_addr           = 0x000,
	.csid_csi2_rx_de_scramble_cfg1_addr           = 0x000,
	.csid_csi2_rx_cap_unmap_long_pkt_hdr_0_addr   = 0x210,
	.csid_csi2_rx_cap_unmap_long_pkt_hdr_1_addr   = 0x214,
	.csid_csi2_rx_captured_short_pkt_0_addr       = 0x218,
	.csid_csi2_rx_captured_short_pkt_1_addr       = 0x21c,
	.csid_csi2_rx_captured_long_pkt_0_addr        = 0x220,
	.csid_csi2_rx_captured_long_pkt_1_addr        = 0x224,
	.csid_csi2_rx_captured_long_pkt_ftr_addr      = 0x228,
	.csid_csi2_rx_captured_cphy_pkt_hdr_addr      = 0x22c,
	.csid_csi2_rx_lane0_misr_addr                 = 0x230,
	.csid_csi2_rx_lane1_misr_addr                 = 0x234,
	.csid_csi2_rx_lane2_misr_addr                 = 0x238,
	.csid_csi2_rx_lane3_misr_addr                 = 0x23c,
	.csid_csi2_rx_total_pkts_rcvd_addr            = 0x240,
	.csid_csi2_rx_stats_ecc_addr                  = 0x244,
	.csid_csi2_rx_total_crc_err_addr              = 0x248,

	.csi2_rst_srb_all                             = 0x0000,
	.csi2_rst_done_shift_val                      = 0,
	.csi2_irq_mask_all                            = 0xFFFFFFF,
	.csi2_misr_enable_shift_val                   = 6,
	.csi2_vc_mode_shift_val                       = 2,
	.csi2_capture_long_pkt_en_shift               = 0,
	.csi2_capture_short_pkt_en_shift              = 1,
	.csi2_capture_cphy_pkt_en_shift               = 2,
	.csi2_capture_long_pkt_dt_shift               = 4,
	.csi2_capture_long_pkt_vc_shift               = 10,
	.csi2_capture_short_pkt_vc_shift              = 1,
	.csi2_capture_cphy_pkt_dt_shift               = 20,
	.csi2_capture_cphy_pkt_vc_shift               = 26,
	.csi2_rx_phy_num_mask                         = 0xf,
};

static struct ais_ife_csid_pxl_reg_offset  ais_ife_csid_780_ipp_reg_offset = {
	.csid_pxl_irq_status_addr            = 0xAC,
	.csid_pxl_irq_mask_addr              = 0xB0,
	.csid_pxl_irq_clear_addr             = 0xB4,
	.csid_pxl_irq_set_addr               = 0xB8,

	.csid_pxl_cfg0_addr                  = 0x300,
	.csid_pxl_cfg1_addr                  = 0x310,
	.csid_pxl_ctrl_addr                  = 0x304,
	.csid_pxl_frm_drop_pattern_addr      = 0x374,
	.csid_pxl_frm_drop_period_addr       = 0x378,
	.csid_pxl_irq_subsample_pattern_addr = 0x37C,
	.csid_pxl_irq_subsample_period_addr  = 0x380,
	.csid_pxl_hcrop_addr                 = 0x35C,
	.csid_pxl_vcrop_addr                 = 0x360,
	.csid_pxl_pix_drop_pattern_addr      = 0x364,
	.csid_pxl_pix_drop_period_addr       = 0x368,
	.csid_pxl_line_drop_pattern_addr     = 0x36C,
	.csid_pxl_line_drop_period_addr      = 0x370,
	.csid_pxl_rst_strobes_addr           = 0x000,
	.csid_pxl_status_addr                = 0x000,
	.csid_pxl_misr_val_addr              = 0x000,
	.csid_pxl_format_measure_cfg0_addr   = 0x384,
	.csid_pxl_format_measure_cfg1_addr   = 0x388,
	.csid_pxl_format_measure0_addr       = 0x38C,
	.csid_pxl_format_measure1_addr       = 0x390,
	.csid_pxl_format_measure2_addr       = 0x394,
	.csid_pxl_timestamp_curr0_sof_addr   = 0x398,
	.csid_pxl_timestamp_curr1_sof_addr   = 0x39C,
	.csid_pxl_timestamp_perv0_sof_addr   = 0x3A0,
	.csid_pxl_timestamp_perv1_sof_addr   = 0x3A4,
	.csid_pxl_timestamp_curr0_eof_addr   = 0x3A8,
	.csid_pxl_timestamp_curr1_eof_addr   = 0x3AC,
	.csid_pxl_timestamp_perv0_eof_addr   = 0x3B0,
	.csid_pxl_timestamp_perv1_eof_addr   = 0x3B4,
	/* configurations */
	.pix_store_en_shift_val              = 14,
	.early_eof_en_shift_val              = 16,
};

static struct ais_ife_csid_pxl_reg_offset  ais_ife_csid_780_ppp_reg_offset = {
	.csid_pxl_irq_status_addr            = 0xCC,
	.csid_pxl_irq_mask_addr              = 0xD0,
	.csid_pxl_irq_clear_addr             = 0xD4,
	.csid_pxl_irq_set_addr               = 0xD8,

	.csid_pxl_cfg0_addr                  = 0xB00,
	.csid_pxl_cfg1_addr                  = 0xB10,
	.csid_pxl_ctrl_addr                  = 0xB04,
	.csid_pxl_frm_drop_pattern_addr      = 0xB74,
	.csid_pxl_frm_drop_period_addr       = 0xB78,
	.csid_pxl_irq_subsample_pattern_addr = 0xB7C,
	.csid_pxl_irq_subsample_period_addr  = 0xB80,
	.csid_pxl_hcrop_addr                 = 0xB5C,
	.csid_pxl_vcrop_addr                 = 0xB60,
	.csid_pxl_pix_drop_pattern_addr      = 0xB64,
	.csid_pxl_pix_drop_period_addr       = 0xB68,
	.csid_pxl_line_drop_pattern_addr     = 0xB6C,
	.csid_pxl_line_drop_period_addr      = 0xB70,
	.csid_pxl_rst_strobes_addr           = 0x000,
	.csid_pxl_status_addr                = 0x000,
	.csid_pxl_misr_val_addr              = 0x000,
	.csid_pxl_format_measure_cfg0_addr   = 0xB84,
	.csid_pxl_format_measure_cfg1_addr   = 0xB88,
	.csid_pxl_format_measure0_addr       = 0xB8C,
	.csid_pxl_format_measure1_addr       = 0xB90,
	.csid_pxl_format_measure2_addr       = 0xB94,
	.csid_pxl_timestamp_curr0_sof_addr   = 0xB98,
	.csid_pxl_timestamp_curr1_sof_addr   = 0xB9C,
	.csid_pxl_timestamp_perv0_sof_addr   = 0xBA0,
	.csid_pxl_timestamp_perv1_sof_addr   = 0xBA4,
	.csid_pxl_timestamp_curr0_eof_addr   = 0xBA8,
	.csid_pxl_timestamp_curr1_eof_addr   = 0xBAC,
	.csid_pxl_timestamp_perv0_eof_addr   = 0xBB0,
	.csid_pxl_timestamp_perv1_eof_addr   = 0xBB4,
	/* configurations */
	.pix_store_en_shift_val              = 14,
	.early_eof_en_shift_val              = 16,
};

static struct ais_ife_csid_rdi_reg_offset ais_ife_csid_780_rdi_0_reg_offset = {
	.csid_rdi_irq_status_addr                 = 0xEC,
	.csid_rdi_irq_mask_addr                   = 0xF0,
	.csid_rdi_irq_clear_addr                  = 0xF4,
	.csid_rdi_irq_set_addr                    = 0xF8,
	.csid_rdi_cfg0_addr                       = 0x500,
	.csid_rdi_cfg1_addr                       = 0x510,
	.csid_rdi_ctrl_addr                       = 0x504,
	.epoch_irq_cfg_addr                       = 0x52C,
	.csid_rdi_frm_drop_pattern_addr           = 0x540,
	.csid_rdi_frm_drop_period_addr            = 0x544,
	.csid_rdi_irq_subsample_pattern_addr      = 0x548,
	.csid_rdi_irq_subsample_period_addr       = 0x54C,
	.csid_rdi_rpp_hcrop_addr                  = 0x550,
	.csid_rdi_rpp_vcrop_addr                  = 0x554,
	.csid_rdi_rpp_pix_drop_pattern_addr       = 0x558,
	.csid_rdi_rpp_pix_drop_period_addr        = 0x55C,
	.csid_rdi_rpp_line_drop_pattern_addr      = 0x560,
	.csid_rdi_rpp_line_drop_period_addr       = 0x564,
	.csid_rdi_rst_strobes_addr                = 0x000,
	.csid_rdi_status_addr                     = 0x000,
	.csid_rdi_misr_val0_addr                  = 0x570,
	.csid_rdi_misr_val1_addr                  = 0x574,
	.csid_rdi_misr_val2_addr                  = 0x578,
	.csid_rdi_misr_val3_addr                  = 0x57C,
	.csid_rdi_format_measure_cfg0_addr        = 0x580,
	.csid_rdi_format_measure_cfg1_addr        = 0x584,
	.csid_rdi_format_measure0_addr            = 0x588,
	.csid_rdi_format_measure1_addr            = 0x58C,
	.csid_rdi_format_measure2_addr            = 0x590,
	.csid_rdi_timestamp_curr0_sof_addr        = 0x594,
	.csid_rdi_timestamp_curr1_sof_addr        = 0x598,
	.csid_rdi_timestamp_prev0_sof_addr        = 0x59C,
	.csid_rdi_timestamp_prev1_sof_addr        = 0x5A0,
	.csid_rdi_timestamp_curr0_eof_addr        = 0x5A4,
	.csid_rdi_timestamp_curr1_eof_addr        = 0x5A8,
	.csid_rdi_timestamp_prev0_eof_addr        = 0x5AC,
	.csid_rdi_timestamp_prev1_eof_addr        = 0x5B0,
	.csid_rdi_byte_cntr_ping_addr             = 0x520,
	.csid_rdi_byte_cntr_pong_addr             = 0x524,
	.epoch0_shift_val                         = 16,
	.rup_aup_mask                             = 0x100010,
};

static struct ais_ife_csid_rdi_reg_offset ais_ife_csid_780_rdi_1_reg_offset = {
	.csid_rdi_irq_status_addr                 = 0xFC,
	.csid_rdi_irq_mask_addr                   = 0x100,
	.csid_rdi_irq_clear_addr                  = 0x104,
	.csid_rdi_irq_set_addr                    = 0x108,
	.csid_rdi_cfg0_addr                       = 0x600,
	.csid_rdi_cfg1_addr                       = 0x610,
	.csid_rdi_ctrl_addr                       = 0x604,
	.epoch_irq_cfg_addr                       = 0x62C,
	.csid_rdi_frm_drop_pattern_addr           = 0x640,
	.csid_rdi_frm_drop_period_addr            = 0x644,
	.csid_rdi_irq_subsample_pattern_addr      = 0x648,
	.csid_rdi_irq_subsample_period_addr       = 0x64C,
	.csid_rdi_rpp_hcrop_addr                  = 0x650,
	.csid_rdi_rpp_vcrop_addr                  = 0x654,
	.csid_rdi_rpp_pix_drop_pattern_addr       = 0x658,
	.csid_rdi_rpp_pix_drop_period_addr        = 0x65C,
	.csid_rdi_rpp_line_drop_pattern_addr      = 0x660,
	.csid_rdi_rpp_line_drop_period_addr       = 0x664,
	.csid_rdi_rst_strobes_addr                = 0x000,
	.csid_rdi_status_addr                     = 0x000,
	.csid_rdi_misr_val0_addr                  = 0x670,
	.csid_rdi_misr_val1_addr                  = 0x674,
	.csid_rdi_misr_val2_addr                  = 0x678,
	.csid_rdi_misr_val3_addr                  = 0x67C,
	.csid_rdi_format_measure_cfg0_addr        = 0x680,
	.csid_rdi_format_measure_cfg1_addr        = 0x684,
	.csid_rdi_format_measure0_addr            = 0x688,
	.csid_rdi_format_measure1_addr            = 0x68C,
	.csid_rdi_format_measure2_addr            = 0x690,
	.csid_rdi_timestamp_curr0_sof_addr        = 0x694,
	.csid_rdi_timestamp_curr1_sof_addr        = 0x698,
	.csid_rdi_timestamp_prev0_sof_addr        = 0x69C,
	.csid_rdi_timestamp_prev1_sof_addr        = 0x6A0,
	.csid_rdi_timestamp_curr0_eof_addr        = 0x6A4,
	.csid_rdi_timestamp_curr1_eof_addr        = 0x6A8,
	.csid_rdi_timestamp_prev0_eof_addr        = 0x6AC,
	.csid_rdi_timestamp_prev1_eof_addr        = 0x6B0,
	.csid_rdi_byte_cntr_ping_addr             = 0x620,
	.csid_rdi_byte_cntr_pong_addr             = 0x624,
	.epoch0_shift_val                         = 16,
	.rup_aup_mask                             = 0x200020,
};

static struct ais_ife_csid_rdi_reg_offset ais_ife_csid_780_rdi_2_reg_offset = {
	.csid_rdi_irq_status_addr                 = 0x10C,
	.csid_rdi_irq_mask_addr                   = 0x110,
	.csid_rdi_irq_clear_addr                  = 0x114,
	.csid_rdi_irq_set_addr                    = 0x118,
	.csid_rdi_cfg0_addr                       = 0x700,
	.csid_rdi_cfg1_addr                       = 0x710,
	.csid_rdi_ctrl_addr                       = 0x704,
	.epoch_irq_cfg_addr                       = 0x72C,
	.csid_rdi_frm_drop_pattern_addr           = 0x740,
	.csid_rdi_frm_drop_period_addr            = 0x744,
	.csid_rdi_irq_subsample_pattern_addr      = 0x748,
	.csid_rdi_irq_subsample_period_addr       = 0x74C,
	.csid_rdi_rpp_hcrop_addr                  = 0x750,
	.csid_rdi_rpp_vcrop_addr                  = 0x754,
	.csid_rdi_rpp_pix_drop_pattern_addr       = 0x758,
	.csid_rdi_rpp_pix_drop_period_addr        = 0x75C,
	.csid_rdi_rpp_line_drop_pattern_addr      = 0x760,
	.csid_rdi_rpp_line_drop_period_addr       = 0x764,
	.csid_rdi_yuv_chroma_conversion_addr      = 0x000,
	.csid_rdi_rst_strobes_addr                = 0x000,
	.csid_rdi_status_addr                     = 0x000,
	.csid_rdi_misr_val0_addr                  = 0x770,
	.csid_rdi_misr_val1_addr                  = 0x774,
	.csid_rdi_misr_val2_addr                  = 0x778,
	.csid_rdi_misr_val3_addr                  = 0x77C,
	.csid_rdi_format_measure_cfg0_addr        = 0x780,
	.csid_rdi_format_measure_cfg1_addr        = 0x784,
	.csid_rdi_format_measure0_addr            = 0x788,
	.csid_rdi_format_measure1_addr            = 0x78C,
	.csid_rdi_format_measure2_addr            = 0x790,
	.csid_rdi_timestamp_curr0_sof_addr        = 0x794,
	.csid_rdi_timestamp_curr1_sof_addr        = 0x798,
	.csid_rdi_timestamp_prev0_sof_addr        = 0x79C,
	.csid_rdi_timestamp_prev1_sof_addr        = 0x7A0,
	.csid_rdi_timestamp_curr0_eof_addr        = 0x7A4,
	.csid_rdi_timestamp_curr1_eof_addr        = 0x7A8,
	.csid_rdi_timestamp_prev0_eof_addr        = 0x7AC,
	.csid_rdi_timestamp_prev1_eof_addr        = 0x7B0,
	.csid_rdi_byte_cntr_ping_addr             = 0x720,
	.csid_rdi_byte_cntr_pong_addr             = 0x724,
	.epoch0_shift_val                         = 16,
	.rup_aup_mask                             = 0x400040,
};

static struct ais_ife_csid_reg_offset ais_ife_csid_780_reg_offset = {
	.cmn_reg          = &ais_ife_csid_780_cmn_reg_offset,
	.csi2_reg         = &ais_ife_csid_780_csi2_reg_offset,
	.ipp_reg          = &ais_ife_csid_780_ipp_reg_offset,
	.ppp_reg          = &ais_ife_csid_780_ppp_reg_offset,
	.rdi_reg = {
		&ais_ife_csid_780_rdi_0_reg_offset,
		&ais_ife_csid_780_rdi_1_reg_offset,
		&ais_ife_csid_780_rdi_2_reg_offset,
		NULL,
		},
	.tpg_reg = NULL,
	.top_reg          = &ais_ife_csid_780_top_reg_info,
	.need_top_cfg     = 0x1,
	.input_core_sel = {
		{
			0x0,
			0x1,
			0x2,
			0x3,
			0x8,
			-1,
			-1,
		},
		{
			0x0,
			0x1,
			0x2,
			0x3,
			-1,
			-1,
			-1,
		},
		{
			0x0,
			0x1,
			0x2,
			0x3,
			-1,
			0x9,
			-1,
		},
	},

};
#endif /*_AIS_IFE_CSID_780_H_ */
