# SPDX-License-Identifier: GPL-2.0-only

CONFIG_SPECTRA_CAMERA := m
CONFIG_SPECTRA_ISP := y
CONFIG_SPECTRA_SENSOR := y
CONFIG_SPECTRA_ICP := y
CONFIG_SPECTRA_JPEG := y
CONFIG_SPECTRA_CUSTOM := y
CONFIG_SPECTRA_LRME := y

# Flags to pass into C preprocessor
ccflags-y += -DCONFIG_SPECTRA_CAMERA=1
ccflags-y += -DCONFIG_SPECTRA_ISP=1
ccflags-y += -DCONFIG_SPECTRA_SENSOR=1
ccflags-y += -DCONFIG_SPECTRA_ICP=1
ccflags-y += -DCONFIG_SPECTRA_JPEG=1
ccflags-y += -DCONFIG_SPECTRA_CUSTOM=1
ccflags-y += -DCONFIG_SPECTRA_LRME=1
